on:
  issues:
    types: [opened]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: LinuxHub-Group/invite-on-label@v1.3.2
        with:
          organization: LinuxHub-Group
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '欢迎来到LinuxHub!'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
